version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - '80:80'
    links:
      - 'flask'
  flask:
      image: 'subacc09/neis_code_finder:0.0.1'
      container_name: flask
      ports:
        - '5000'
